import { sqcp_mapping } from '../types';
import identity from './identity';
import utm from './utm';
import owner from './owner';

const m: sqcp_mapping = {
    ...identity,
    ...utm,
    ...owner,
    tenant: { key: 't', type: 'string' },
    paymentMean: { key: 'p', type: 'code' },
    quantity: { key: 'q', type: 'integer' },
    donation: { key: 'd', type: 'integer' },
    custom: { key: 'cd', type: 'string' },
    customSeller: { key: 'sc', type: 'string' },
    mode: { key: 'm', type: 'code' },
    locale: { key: 'l', type: 'locale' },
    game: { key: 'g', type: 'string' },
    sellergroup: { key: 'sg', type: 'string' },
    seller: { key: 's', type: 'string' },
    pack: { key: 'pk', type: 'string' },
    godfather: { key: 'z', type: 'string' },
    project: { key: 'pr', type: 'string' },
    beneficiary: { key: 'b', type: 'string' },
    country: { key: 'c', type: 'country' },
    book: { key: 'k', type: 'string' },
    bookPublicToken: { key: 'kpt', type: 'publicToken' },
    requestedTicketCustomCodes: { key: 'cc', type: 'string' },
    // registration
    gameName: { key: 'gna', type: 'string' },
    gameTheme: { key: 'gth', type: 'string' },
    gameSubject: { key: 'gsu', type: 'string' },
    organizationName: { key: 'ona', type: 'string' },
    city: { key: 'ci', type: 'string' },
    zipCode: { key: 'zc', type: 'string' },
    organizationType: { key: 'oty', type: 'string' },
    ticketPriceAmount: { key: 'tpa', type: 'integer' },
    ticketPriceCurrency: { key: 'tpc', type: 'string' },
    facebookUrl: { key: 'fbu', type: 'url' },
    websiteUrl: { key: 'wsu', type: 'url' },
    plannedStartedAt: { key: 'psat', type: 'datetime' },
    plannedDrawnAt: { key: 'pdat', type: 'datetime' },
    gameOptions: { key: 'gopts', type: 'string' },
    saleData: { key: 'sad', type: 'string' },
    supportedLocales: { key: 'slcs', type: 'string' },
    plannedTickets: { key: 'ptk', type: 'integer' },
    plannedCustomTickets: { key: 'pctk', type: 'integer' },
    logoImage: { key: 'lim', type: 'image' },
    bannerImage: { key: 'bim', type: 'image' },
    gimage1Image: { key: 'g1im', type: 'image' },
    gimage2Image: { key: 'g2im', type: 'image' },
    gimage3Image: { key: 'g3im', type: 'image' },
    gimage4Image: { key: 'g4im', type: 'image' },
    gimage5Image: { key: 'g5im', type: 'image' },
    gimage6Image: { key: 'g6im', type: 'image' },
    gimage7Image: { key: 'g7im', type: 'image' },
    gimage8Image: { key: 'g8im', type: 'image' },
    gamePresentation: { key: 'gpr', type: 'string' },
    templateGameCode: { key: 'tgc', type: 'string' },
    templateGame: { key: 'tg', type: 'string' },
    templateGameProperties: { key: 'tgp', type: 'string' },
    organizationPresentation: { key: 'opr', type: 'string' },
};

export default m;
